spring:
  application:
    name: aggregation-worker
  main:
    web-application-type: none
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/healthplus?reWriteBatchedInserts=true}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:healthplus}
    password: ${DB_PASSWORD:healthplus}
  jpa:
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY:sk-827de10d100d4975bff6be873024b4d7}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
