version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: healthplus-postgres
    environment:
      POSTGRES_DB: healthplus
      POSTGRES_USER: healthplus
      POSTGRES_PASSWORD: healthplus
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: healthplus-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7
    container_name: healthplus-redis
    ports:
      - "16379:6379"

  minio:
    image: minio/minio:latest
    container_name: healthplus-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
