spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/healthplus?reWriteBatchedInserts=true
    username: ${DB_USERNAME:healthplus}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}
  data:
    redis:
      host: redis
      port: 6379
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
app:
  storage:
    root: /data
    type: ${STORAGE_TYPE:local}
    s3:
      endpoint: http://minio:9000
      region: us-east-1
      access-key: ${MINIO_ACCESS_KEY:minioadmin}
      secret-key: ${MINIO_SECRET_KEY:minioadmin}
      bucket: healthplus
